document.addEventListener('DOMContentLoaded',()=>{
const style=document.createElement('style');style.textContent=`
.category-modal{position:fixed;inset:0;z-index:9999;display:none;overflow-y:auto;background:rgba(18,14,11,.97);color:#f5f1eb;padding:8vh 6vw}
.category-modal.open{display:block!important}
.category-modal-inner{max-width:1200px;margin:0 auto;position:relative}
.category-close{position:absolute;right:0;top:-12px;width:48px;height:48px;border:1px solid rgba(255,255,255,.35);border-radius:50%;background:transparent;color:#fff;font-size:30px;line-height:1;cursor:pointer;z-index:10}
.category-head{padding:0 70px 42px 0}.category-kicker{font-size:10px;letter-spacing:.2em;text-transform:uppercase;opacity:.65}.category-head h2{font:500 clamp(48px,7vw,90px)/.95 'Playfair Display';letter-spacing:-.04em;margin:18px 0}.category-head p{max-width:560px;font-size:14px;line-height:1.7;color:rgba(245,241,235,.7)}
.category-grid{display:grid;grid-template-columns:repeat(12,1fr);grid-auto-rows:80px;gap:14px}.category-shot{position:relative;border:0;padding:0;overflow:hidden;background:#28231f;color:#fff;cursor:zoom-in;min-width:0}.category-shot img{width:100%;height:100%;display:block;object-fit:cover}.category-shot span{position:absolute;left:18px;bottom:16px;font-size:9px;text-transform:uppercase;letter-spacing:.14em;text-shadow:0 1px 10px #000;z-index:2}.category-shot:after{content:'';position:absolute;inset:0;background:linear-gradient(0deg,rgba(0,0,0,.5),transparent 55%);pointer-events:none}.category-shot.featured{grid-column:span 7;grid-row:span 6}.category-shot:not(.featured){grid-column:span 5;grid-row:span 4}
@media(max-width:800px){.category-modal{padding:70px 5vw 30px}.category-modal-inner{width:100%}.category-close{right:0;top:-6px}.category-head{padding-right:55px}.category-head h2{font-size:50px;line-height:.95}.category-head p{font-size:12px;line-height:1.7}.category-grid{grid-template-columns:repeat(2,minmax(0,1fr));grid-auto-rows:170px;gap:10px}.category-shot,.category-shot:not(.featured){grid-column:span 1;grid-row:span 2}.category-shot.featured{grid-column:span 2;grid-row:span 3}.category-shot span{left:14px;bottom:13px;font-size:8px}}
`;document.head.appendChild(style);
const sets={
 wedding:{title:'Weddings',intro:'Celebrations, details and portraits from the wedding portfolio.',images:[['Gorgeous-Assamese-Bride.jpg','Assamese Bride'],['Gorgeous-Bihari-Bride-In-Lehenga.jpg','Bride in Lehenga'],['Handsome-Nepali-Groom(1).jpg','Groom Portrait'],['Beautiful-Wedding-Album.jpg','Wedding Album'],['Brides-Hand-With-Mehndi.jpg','Mehndi Details']]},
 pre:{title:'Pre-Weddings',intro:'Natural moments and couple stories before the vows.',images:[['Couple-Playing-With-Water.jpg','Playful Moments'],['Couple-Photograph-In-Autumn-Look.jpg','Autumn Couple'],['Boy-Lifting-Girl-In-His-Arms.jpg','Together'],['I-Love-You(1).jpg','I Love You']]},
 portrait:{title:'Portraits',intro:'Personal portraits, fashion and expressive frames.',images:[['Gorgeous-Assamese-Lady.jpg','Portrait'],['Moody-Fashion-Portrait(1).jpg','Moody Fashion'],['Bihu-Theme-Model-Shoot.jpg','Bihu Theme'],['Handsome-Nepali-Groom(1).jpg','Groom Portrait'],['FB_IMG_1788539249228.jpg','Portrait Session']]},
 film:{title:'Films & Reels',intro:'Cinematic stills and visual storytelling.',images:[['Boy-Lifting-Girl-In-His-Arms.jpg','Cinematic Moment'],['Couple-Playing-With-Water.jpg','Motion & Memory'],['I-Love-You(1).jpg','Couple Story'],['Beautiful-Wedding-Album.jpg','Wedding Story']]},
 maternity:{title:'Maternity & Baby',intro:'Tender maternity portraits and beautiful first moments for growing families.',images:[['FB_IMG_1788539226339.jpg','Mother & Baby'],['FB_IMG_1788539218668.jpg','Maternity Portrait'],['FB_IMG_1788539223513.jpg','Baby Portrait'],['FB_IMG_1788539229859.jpg','Baby Moments'],['FB_IMG_1788539232066.jpg','Family Story'],['FB_IMG_1788539240643.jpg','Little One'],['FB_IMG_1788539243051.jpg','Baby Portrait'],['FB_IMG_1788539205142.jpg','Maternity Story']]}
};
let modal=document.querySelector('.category-modal');
if(!modal){modal=document.createElement('div');modal.className='category-modal';modal.innerHTML='<div class="category-modal-inner"><button class="category-close" type="button">×</button><div class="category-head"><span class="category-kicker">Soulful Pixels Photography</span><h2></h2><p></p></div><div class="category-grid"></div></div>';document.body.appendChild(modal)}
const title=modal.querySelector('h2'),intro=modal.querySelector('.category-head p'),grid=modal.querySelector('.category-grid');
function open(key){const set=sets[key];if(!set)return;title.textContent=set.title;intro.textContent=set.intro;grid.innerHTML=set.images.map((x,i)=>`<button class="category-shot ${i===0?'featured':''}" type="button"><img src="${x[0]}" alt="${x[1]}"><span>${x[1]}</span></button>`).join('');modal.classList.add('open');document.body.style.overflow='hidden';grid.querySelectorAll('.category-shot').forEach((s,i)=>{if(key==='maternity'&&i===1)s.querySelector('img').style.objectPosition='center 28%';s.onclick=()=>{const img=s.querySelector('img');const lb=document.querySelector('.lightbox');if(lb){const li=lb.querySelector('img');li.src=img.src;li.alt=img.alt;lb.classList.add('open');lb.setAttribute('aria-hidden','false')}}})}
function close(){modal.classList.remove('open');document.body.style.overflow=''}
modal.querySelector('.category-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
const map={wedding:'wedding',pre:'pre',portrait:'portrait',film:'film',maternity:'maternity'};
Object.entries(map).forEach(([cls,key])=>document.querySelectorAll('.'+cls).forEach(card=>{card.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open(key)})}));
});